### ISSUE TITLE
Multiple log-out

### ISSUE THREAD

**Issue by supermamie** [YunoHost-Apps/freshrss_ynh#68]
I don't know if this is due to yunohost 3.5 or freshrss 1.14.1, but since this, I am really often logged out FreshRss.
This only happens to FreshRss, no other app have this problem.

I don't know what I can provide to help solve this :(

**Comment by Alkarex** [comment]
@plopoyop The package is using the HTTP Basic Auth method, right?

**Comment by plopoyop** [comment]
@Alkarex Yes, It does.

@supermamie , I use the last version of ynh and don't have this problem.
Are you logged out from the SSO too ? or just from freshrss ?

**Comment by supermamie** [comment]
When I'm logged out, I am redirected to the yunohost SSO, so I don't really know the source of the problem.
This is not easy to reproduce, sometime it is frequent, but right now, I have not been disconnected for ~4h

**Comment by lapineige** [comment]
Same Yunohost 3.5 and FreshRSS 1.14.1, I have the same issue: I'm logged out each time I reload the page or load another freshRSS page.
Redirected to the SSO each time.

I tested with Firefox, even without any extension.

**Comment by supermamie** [comment]
Just for info if it can help, after the update I changed `security.nginx.compatibility` to modern.

**Comment by plopoyop** [comment]
> security.nginx.compatibility

where is this parameter ?

**Comment by supermamie** [comment]
https://yunohost.org/#/security
`sudo yunohost settings set security.nginx.compatibility -v modern`
It should not change anything other than https config, but it may be a source of problem in a way or another, I don't know :(

**Comment by lapineige** [comment]
And in my case, I didn't change it, it's a custom one close to the modern one (a bit more restrictive).

**Comment by plopoyop** [comment]
I don't think it is related.
Freshrss is only reading the http basic auth header. There isn't even a logout button.

With the 3.5 upgrade, I saw the SSOWAT user panel came back (for some reason it was blocked by my browser in earlyer version)
Maybe it is related. Can you try to comment the line `include conf.d/yunohost_panel.conf.inc;` in : `/etc/nginx/youdomain.d/freshrss.conf`  and then `sudo systemctl restart nginx.service`

Just in case.

**Comment by supermamie** [comment]
As soon as it came back, I disabled it (globally, not just for FreshRSS)

**Comment by lapineige** [comment]
>  (for some reason it was blocked by my browser in earlyer version)

That was fixed by Yunohost 3.5

**Comment by supermamie** [comment]
When an icon is not loaded, that means you have been logged out.
Refresh to log-in again

**Comment by lapineige** [comment]
Yeah, that's the problem… I log in, then I don't have the icons, and any reload or load of any feed log me out.

**Comment by supermamie** [comment]
On my side, I'm not logged out on each request, just really frequently.

**Comment by lapineige** [comment]
That behaviour is really strange…

**Comment by lapineige** [comment]
Is there any log that we could provide @plopoyop ?

**Comment by plopoyop** [comment]
I have absolutly no idea.

Is it possible for you to open a browser without any extention activated, log in only freshrss and wait to see if the problem happen. 
I want to be sure the problem come only from freshrss and not from another yunohost app, or from a browser privacy extention.

I really can't find any reason for this to happen.

**Comment by lapineige** [comment]
I checked with Firefox Nightly (with extensions) and Tor Browser (without extension), nothing appends.

Just in case: I restored FreshRSS from a few months old backup, then updated. Could this be related ?
I'll try an install in another server and see if my main browser has the same problem.

**Comment by plopoyop** [comment]
> I checked with Firefox Nightly (with extensions) and Tor Browser (without extension), nothing appends.
nothing appends as in "there is no logout probem ?" or as "there is no difference with my usual browser"


> 
> Just in case: I restored FreshRSS from a few months old backup, then updated. Could this be related ?
I never tried a restore except during my tests. The package check says the restore does not work. That's one reason I am trying to refactor the whole package

> I'll try an install in another server and see if my main browser has the same problem.
> edit: and I don't have any problem with that fresh (ahah) new instance.
So fresh(rss) ;) install has no problem but restore has.
@supermamie : do you have a fresh install or is it a restored backup ?

**Comment by lapineige** [comment]
> nothing appends as in "there is no logout probem ?" or as "there is no difference with my usual browser"

Oh yeah sorry ^^
Same issue, I'm logged out.

> I never tried a restore except during my tests. The package check says the restore does not work. That's one reason I am trying to refactor the whole package

Oh… ok.
Then we'll need to find out what's wrong…

**Comment by plopoyop** [comment]
> Do you have the log link ?

No, yunohost CI seems down as nearly no package pass.

**Comment by plopoyop** [comment]
Hi,
Can you please upgrade using the branch feature/complete-refactor please ? 

I tried to backup / restore and have no logout problem.
I couldn't check if I have the problem with current master branch because restore is broken.

I'll merge this branch as soon as I'll have done enough testing

**Comment by lapineige** [comment]
Done.
The issue is still there :(

A quick note: php service was stopped right after the upgrade. I didn't check if it is caused by the upgrade.

**Comment by plopoyop** [comment]
It makes no sense :(

Do you have php service log please ?

**Comment by lapineige** [comment]
I tried to upgrade again (from the same version), the service was still active.
It doesn't seem to be related.

**Comment by plopoyop** [comment]
I don't really know.
Maybe all the logs you can provide at the exact time of the logout.
We need to know if freshrss is sending a logout request (I doubt about that since it is setup with http auth, therefore there is no logout button).

I'd love to know if @supermamie is in the same use case as you : installed from a backup.

**Comment by supermamie** [comment]
I don't think so, but when I set up my server I tried multiple ways of douing things so it might be possible (but it was more than one year ago)

**Comment by plopoyop** [comment]
@lapineige : The version of package I made you upgrade to is buggy and your cron must be broken now.
I fixed it in my latest commit. You can upgrade again if you want to fix it.

**Comment by lapineige** [comment]
Done, thanks :)

**Comment by lapineige** [comment]
Btw, when I load the page (after login in), it does load the icons and clicking on a feed (which should mark is as read) give an error message, the same as when you have no internet connection.

**Comment by lapineige** [comment]
Ok I just realised that my FreshRSS didn't update the feed since the 24th of May. I think it was when I restored the backup.

There is definitely something broken in that backup :(

**Comment by lapineige** [comment]
Now my feed are updated as expected. Still can't connect correctly / I'm disconnected directly.
And the API doesn't work.


As I don't know how to solve that issue, I wonder if I can find a solution to bypass it.

Is it possible for me to do a fresh(rss :D) install and then import the database, the restore my feed list and so on ?
(if yes, could you guide me briefly about the way to do that ?)

**Comment by lapineige** [comment]
I don't believe it…
I just tried to connect again, same error as usual (no icons, can't mark an article as read), then selected another feed category, had to log-in again (as usual with this issue), and then… it works normally 😲

**Comment by supermamie** [comment]
Still many random logout on my side.
Some times it's on every click, sometime I'm logged for hours, and it only seems to happens with freshrss (I always have riot in another tab, and nextcloud too, without any problems)

**Comment by Alkarex** [comment]
Could one of you make me a test account on your instance facing the problem?

**Comment by SuperSandro2000** [comment]
I noticed this behavior recently on my instance, too. Everytime I boot up my laptop I get logged out. I can't provide you with an account right now due to technical reasons I get fixed soon ™️ . If I can test anything for you, provide logs or something else let me know and I try my best to get this fixed.

**Comment by supermamie** [comment]
@Alkarex how can I send you some credentials ?

**Comment by supermamie** [comment]
I don't know if there was an update I didn't notice, but I do not have anymore those random log-out.
I changed the "Image Proxy" extension a few days ago to point to a proxy hosted on my machine, and selected to use it even in https.
Since that (I think), I'm logged in without any problem...

**Comment by supermamie** [comment]
Right after the previous message I was logged out :cry:

**Comment by manuc66** [comment]
@Alkarex I can send you credentials too if you want

I suspect that it is related to the number http calls (related to the number of feeds) 

I can see this error message : `La ressource à l’adresse « https://xxxxx.xxxxx.xxx/yunohost/sso/ » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).` that is a consequence of a call to `https://xxxxx.xxxxx.xxx/rss/f.php?e37acdf1` that ends with a `302` status code with a redirect to `https://xxxxx.xxxxx.xxx/yunohost/sso/?r=aHR0cHM6Ly9tYWWWYzY2LmR1Y2tkbnMub3JnL3Jzcy9mLnBocD9lMzdhY2RMMT10cnVl`

**Comment by lapineige** [comment]
Hello,

I tried with FreshRSS android app, and while the app can retrieve the list of categories and the number of not-read articles, it can't retrieve articles (or at least their content, I don't know).

I suppose it's the same issue as this one.

**Comment by supermamie** [comment]
Not at all, this is a bug on the app side, ticket opened and will be fixed on next version.
(Not 100% sure, you'll have to compare the app logs with the log provided in the ticket in the app's repo)

On another side, I have another app where I am frequently logged out (Monitorix).
In this app, there are a lot of images displayed, without any cache (they represent the server status so caching clientside is blocked)

Maybe the sites icons in freshrss are not cached and create a lot of calls simualtenousely which mby trigger a logout somewhere ?

**Comment by Alkarex** [comment]
`https://yno.example.net/rss/f.php?...` is not supposed to be SSO'ed.

There is an option to disable favicons https://github.com/FreshRSS/FreshRSS/pull/2821 if you like to test whether that makes any difference.

**Comment by lapineige** [comment]
I just updated to the lastest 1.16.2, and the issue seems magically gone…

**Comment by manuc66** [comment]
@lapineige same for me !

**Comment by manuc66** [comment]
> 
> 
> I just updated to the lastest 1.16.2, and the issue seems magically gone…

Same for me

**Comment by lapineige** [comment]
I took a look at the changelog, and I wonder if it's not linked to https://github.com/FreshRSS/FreshRSS/pull/2961

Anyway, problem solved, thanks a lot @Alkarex and @plopoyop !
